#ifndef CHARACTER_SHEET_SCREEN_H
#define CHARACTER_SHEET_SCREEN_H

const enum CharacterSheetPointerStates {STR_CS, DEX_CS, CON_CS, INT_CS, WIS_CS, CHA_CS, HP_CS, ATTACK_BONUS_CS, RANGED_DEFENSE_CS, MELEE_DEFENSE_CS, TRAUMA_CS, FORT_CS, REFLEX_CS, WILLPOWER_CS, LUCK_CS, TOTAL_HP_CS, SS_CS, TOTAL_SS_CS, EURODOLLARS_CS, ADM_CS, CON_CS, DRV_CS, EXR_CS, PERFORMER, SOLDIER, SPY, TRADER, STREETWALKER, TECHNICIAN};

void InitCharacterSheet(void);
uint8_t CharacterSheetUpdate(void);

#endif