#ifndef CHARACTER_SHEET_SCREEN_H
#define CHARACTER_SHEET_SCREEN_H

const enum CharacterSheetNumbers {MINUS_THREE, MINUS_TWO, MINUS_ONE, PLUS_MINUS_ZERO, PLUS_ONE, PLUS_TWO, PLUS_THREE, PLUS_FOUR, ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, ELEVEN, TWELVE, THIRTEEN, FOURTEEN};

const enum CharacterSheetPointerStates {STRENGTH_CS, DEXTERITY_CS, CONSTITUTION_CS, INTELLIGENCE_CS, WISDOM_CS, CHARISMA_CS, HP_CS, ATTACK_BONUS_CS, RANGED_DEFENSE_CS, MELEE_DEFENSE_CS, TRAUMA_CS, FORT_CS, REFLEX_CS, WILLPOWER_CS, LUCK_CS, TOTAL_HP_CS, SS_CS, TOTAL_SS_CS, EURODOLLARS_CS, ADMINISTER_CS, CONNECT_CS, DRIVE_CS, EXERT_CS, FIX_CS, HEAL_CS, KNOW_CS, LEAD_CS, NOTICE_CS, PERFORM_CS, PROGRAM_CS, PUNCH_CS, SHOOT_CS, SNEAK_CS, STAB_CS, SURVIVE_CS, TALK_CS, TRADE_CS, WORK_CS, INVENTORY_CS, HEAT_CS};

void InitCharacterSheet(void);
void UpdateCharacterSheetStats(void);
uint8_t CharacterSheetUpdate(void);
uint8_t CharacterSheetPointerUpdate(void);
uint8_t CharacterSheetInventoryPointerUpdate(void);
void DefineSheetStat(void);


#endif