//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_FONT_H
#define METASPRITE_FONT_H

#define Font_TILE_ORIGIN 0
#define Font_TILE_W 8
#define Font_TILE_H 8
#define Font_WIDTH 416
#define Font_HEIGHT 8
#define Font_sprite_size 59
#define Font_sprite_start 197
#define DIALOG_WIDTH 18
#define DIALOG_HEIGHT 3
#define DIALOG_INIT_X 1
#define DIALOG_INIT_Y 1
#define DIALOG_WIN_HEIGHT 106
//#define DIALOG_DELAY 1

//BANKREF_EXTERN(Font)

extern uint8_t DIALOG_DELAY;
extern const unsigned char Font_symbols[25];

void dialog_init(void);

void dialog_print_p(unsigned char *name, uint8_t name_size, unsigned char *text, uint8_t size);

void dialog_print(unsigned char *text, uint8_t size);

void screen_print(unsigned char *text, uint8_t size);

#endif
