//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Font_H
#define METASPRITE_Font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Font_TILE_ORIGIN 0
#define Font_TILE_W 8
#define Font_TILE_H 8
#define Font_WIDTH 416
#define Font_HEIGHT 8
#define Font_sprite_size 59
#define Font_sprite_start 0
#define DIALOG_WIDTH 18
#define DIALOG_HEIGHT 5
#define DIALOG_INIT_X 1
#define DIALOG_INIT_Y 1
#define DIALOG_WIN_HEIGHT 106
//#define DIALOG_DELAY 1

#define VBlankDelay(d) for (uint8_t i=0; i<d; i++) vsync();

BANKREF_EXTERN(Font)

extern uint8_t DIALOG_DELAY;
extern const unsigned char Font_symbols[25];

void dialog_print(unsigned char *text, uint8_t size);

void screen_print(unsigned char *text, uint8_t size);

#endif
