/*

 DEATHMASK_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 158

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __DeathMask_tiles_h_INCLUDE
#define __DeathMask_tiles_h_INCLUDE

/* Bank of tiles. */
#define DeathMask_tilesBank 1
/* Start of tile array. */
extern const void __bank_DeathMask_tiles;
extern const unsigned char DeathMask_tiles[];

#endif

/* End of DEATHMASK_TILES.H */
