/*

 NICKANDWOLF_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 20 x 18
   Tile set      : X:\GameBoy\CwN-GBDK\res\NandW_logo.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __NickAndWolf_map_h_INCLUDE
#define __NickAndWolf_map_h_INCLUDE

#define NickAndWolf_mapWidth 20
#define NickAndWolf_mapHeight 18
#define NickAndWolf_mapBank 1

extern const void __bank_NickAndWolf_map;
extern const unsigned char NickAndWolf_map[];

#endif

/* End of NICKANDWOLF_MAP.H */
