#ifndef GAME_STATES_ENUM_H
#define GAME_STATES_ENUM_H

//briefing and notes are shitty and gonna figure that out later

const enum GAME_STATE_SCENES {CHAR_SHEET_STATE, BRIEFING_SHEET_STATE, NOTES_SHEET_STATE, HELP_SHEET_STATE, EXIT_PLAYER_HOUSE_INVENTORY, PLAYING_STATE, TITLE_SCREEN_STATE, HOSPITAL_1_STATE, APARTMENT_1_STATE};

#endif