/*

 CHARACTER_SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 23

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Character_Sprite_h_INCLUDE
#define __Character_Sprite_h_INCLUDE

/* Bank of tiles. */
#define CharacteSpriteBank 0
/* Start of tile array. */
extern const unsigned char CharacterSprite[];

#endif

/* End of CHARACTER_SPRITE.H */
