/*

 DIALOG_FRAME.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 5
   Tile set      : customFont.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __dialog_frame_h_INCLUDE
#define __dialog_frame_h_INCLUDE

#define dialog_frameWidth 20
#define dialog_frameHeight 5

extern const unsigned char dialog_frame[];

#endif

/* End of DIALOG_FRAME.H */
