/*

 ROLL_PRESSA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : X:\GameBoy\CwN-GBDK\res\dice.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __roll_pressA_h_INCLUDE
#define __roll_pressA_h_INCLUDE

#define roll_pressAWidth 4
#define roll_pressAHeight 4
#define roll_pressABank 0

extern const unsigned char roll_pressA[];

#endif

/* End of ROLL_PRESSA.H */
