/*

 ROLL_PRESSA.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : X:\GameBoy\CwN-GBDK\res\dice.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define roll_pressAWidth 4
#define roll_pressAHeight 4
#define roll_pressABank 0

const unsigned char roll_pressA[] =
{
  0x10
};

/* End of ROLL_PRESSA.C */
