//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>
#include "inc/Font.h"
#include "../res/dialog_frame.h"
#include "../res/CustomFont.h"
#include <gb/gb.h>
#include "inc/MainCharacter.h"


BANKREF(Font)

uint8_t DIALOG_DELAY = 1;

/*

question mark 	= /
elipses 		= #
coin			= $
more dialog		= &
end dialog		= *
*/

const unsigned char Font_symbols[25] = {
	'!', '"', '#', '$', '%', '&', 39, '(', ')', '*', '+', ',', '-', '.', '/',
	'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
};

void dialog_print_p(unsigned char *name, uint8_t name_size, unsigned char *text, uint8_t size) {
	set_win_data(0,59,CustomFont);
	init_win(0x00);//wipe the screen
	set_win_tiles(0,0,20,5,dialog_frame);//throw up a fresh border
	SHOW_WIN;//display to the world
	
	//We wanna scroll up so we set the end point and move there
	uint8_t y = 160;
	while (y > DIALOG_WIN_HEIGHT) {
		move_win(7,y);
		y-=3;//the means the window could end up in the wrong spot, we correct that below
		//VBlankDelay(DIALOG_DELAY)
		vsync();
	}
	move_win(7,DIALOG_WIN_HEIGHT); //then we make sure it ends where it's supposed to be
	
	//we need to hide the player if he's in the wrong spot.
	int8_t tempPlayerY = 160; //TODO: All sprites will need to do this...
	if (playerY > DIALOG_WIN_HEIGHT-12) {
		move_sprite(0, playerX+8, tempPlayerY+16);
        move_sprite(2, playerX+16, tempPlayerY+16);
	}
	
	//PUT A DUDE'S NAME
	uint8_t name_xpos=0, name_ypos=0;
	uint8_t name_index = 0;
	
	while (name_index < name_size-1) {
		const unsigned char *name_current = &name[name_index];
		set_win_tile_xy(name_xpos, name_ypos, (*name_current-0x47+Font_sprite_start));
		name_xpos++;
		name_index++;
	}
	
	
    // This is an imaginary cursor.
	uint8_t xpos=0, ypos=0;
    // This is the string index.
	uint8_t index=0;

	while (index-0<(size-1))
	{
        // This do a line jump if there's no more space on tile width (can be personalized).
		if (xpos % DIALOG_WIDTH == 0) {xpos=1; ypos++;}
		else xpos++;

        // This is the string index.
		(xpos == 1 && text[index] == ' ')?index++:index;

        // This put a - sign if there's no width space and a word isn't finished.
		if (xpos == DIALOG_WIDTH && text[index] != ' ' && text[index+1] != ' ') {
			set_win_tile_xy(xpos, ypos, ('-'-0x20+Font_sprite_start)); xpos=1; ypos++;
		}
		
		(xpos == 1 && text[index] == ' ')?index++:index;
        
		// This variable sets the current character of the string based on its index.
		const unsigned char *current = &text[index];
		
        // This fills the canvas with an empty tile if there's no more space.
        // Note that it uses the 0x00 tile.
		if (ypos > DIALOG_HEIGHT) {
				set_win_tile_xy(19,3,0x06);
				waitpadup();
				waitpad(J_A);
				//init_win(0xCC);
				fill_win_rect(DIALOG_INIT_X, DIALOG_INIT_Y, DIALOG_WIDTH, DIALOG_HEIGHT, 0x00);
				xpos=ypos=1;
				set_win_tile_xy(19,3,0x39);
			}

        // This print the letters.
		if (*current != ' ') set_win_tile_xy(xpos, ypos, (*current-0x47+Font_sprite_start));
		
		
        // This print the symbols.
		for (uint8_t i=0; i<(sizeof(Font_symbols)); i++)
			if (*current == Font_symbols[i]) set_win_tile_xy(xpos, ypos, (*current-0x20+Font_sprite_start));
		
        VBlankDelay(DIALOG_DELAY);

		index++;
	}
	
	//we don't have buttons to accidentially close dialog
	set_win_tile_xy(19,3,0x0A);
	waitpadup();
	waitpad(J_A);
	
	//put player back
	if (playerY > DIALOG_WIN_HEIGHT-12) {
		move_sprite(0, playerX+8, playerY+16);
        move_sprite(2, playerX+16, playerY+16);
	}
	
	//scroll it back down!
	y = DIALOG_WIN_HEIGHT;
	while (y < 160) {
		move_win(7,y);
		y+=3;
		//VBlankDelay(DIALOG_DELAY)
		vsync();
	}
	move_win(7,160);
	HIDE_WIN;
}

void dialog_print(unsigned char *text, uint8_t size) {
	set_win_data(0,59,CustomFont);
	init_win(0x00);//wipe the screen
	set_win_tiles(0,0,20,5,dialog_frame);//throw up a fresh border
	SHOW_WIN;//display to the world
	
	//We wanna scroll up so we set the end point and move there
	uint8_t y = 160;
	while (y > DIALOG_WIN_HEIGHT) {
		move_win(7,y);
		y-=3;//the means the window could end up in the wrong spot, we correct that below
		//VBlankDelay(DIALOG_DELAY)
		vsync();
	}
	move_win(7,DIALOG_WIN_HEIGHT); //then we make sure it ends where it's supposed to be
	
	//we need to hide the player if he's in the wrong spot.
	int8_t tempPlayerY = 160; //TODO: All sprites will need to do this...
	if (playerY > DIALOG_WIN_HEIGHT-12) {
		move_sprite(0, playerX+8, tempPlayerY+16);
        move_sprite(2, playerX+16, tempPlayerY+16);
	}
	
    // This is an imaginary cursor.
	uint8_t xpos=0, ypos=0;
    // This is the string index.
	uint8_t index=0;

	while (index-0<(size-1))
	{
        // This do a line jump if there's no more space on tile width (can be personalized).
		if (xpos % DIALOG_WIDTH == 0) {xpos=1; ypos++;}
		else xpos++;

        // This is the string index.
		(xpos == 1 && text[index] == ' ')?index++:index;

        // This put a - sign if there's no width space and a word isn't finished.
		if (xpos == DIALOG_WIDTH && text[index] != ' ' && text[index+1] != ' ') {
			set_win_tile_xy(xpos, ypos, ('-'-0x20+Font_sprite_start)); xpos=1; ypos++;
		}
		
		(xpos == 1 && text[index] == ' ')?index++:index;
        
		// This variable sets the current character of the string based on its index.
		const unsigned char *current = &text[index];
		
        // This fills the canvas with an empty tile if there's no more space.
        // Note that it uses the 0x00 tile.
		if (ypos > DIALOG_HEIGHT) {
				set_win_tile_xy(19,3,0x06);
				waitpadup();
				waitpad(J_A);
				//init_win(0xCC);
				fill_win_rect(DIALOG_INIT_X, DIALOG_INIT_Y, DIALOG_WIDTH, DIALOG_HEIGHT, 0x00);
				xpos=ypos=1;
				set_win_tile_xy(19,3,0x39);
			}

        // This print the letters.
		if (*current != ' ') set_win_tile_xy(xpos, ypos, (*current-0x47+Font_sprite_start));
		
		
        // This print the symbols.
		for (uint8_t i=0; i<(sizeof(Font_symbols)); i++)
			if (*current == Font_symbols[i]) set_win_tile_xy(xpos, ypos, (*current-0x20+Font_sprite_start));
		
        VBlankDelay(DIALOG_DELAY);

		index++;
	}
	
	//we don't have buttons to accidentially close dialog
	set_win_tile_xy(19,3,0x0A);
	waitpadup();
	waitpad(J_A);
	
	//put player back
	if (playerY > DIALOG_WIN_HEIGHT-12) {
		move_sprite(0, playerX+8, playerY+16);
        move_sprite(2, playerX+16, playerY+16);
	}
	
	//scroll it back down!
	y = DIALOG_WIN_HEIGHT;
	while (y < 160) {
		move_win(7,y);
		y+=3;
		//VBlankDelay(DIALOG_DELAY)
		vsync();
	}
	move_win(7,160);
	HIDE_WIN;
}